name: Pipeline Calculadora Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  liberacion:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Generar entorno de liberación
        run: bash scripts/setup_env.sh

      - name: Ejecutar pruebas en entorno de liberación
        run: bash scripts/test_release.sh

      - name: Generar despliegue
        run: bash scripts/deploy.sh